// user
export const USER_SET_USER_TOKEN = 'USER_SET_USER_TOKEN'
export const USER_SET_USER_INFO = 'USER_SET_USER_INFO'


// tagsView
export const TAGSVIEW_ADD_TAG = 'TAGSVIEW_ADD_TAG'
export const TAGSVIEW_DEL_TAG = 'TAGSVIEW_DEL_TAG'
export const TAGSVIEW_CLOSE_OTHER_TAGS = "TAGSVIEW_CLOSE_OTHER_TAGS";
export const TAGSVIEW_CLOSE_ALL = 'TAGSVIEW_CLOSE_ALL'

// app
export const HEADER_SET_FIXED = 'HEADER_SET_FIXED'
export const SIDER_SET_ISOPEN = 'SIDER_SET_ISOPEN'
export const SET_SIDE_BAR_ROUTES = 'SET_SIDE_BAR_ROUTES'